import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const grimReaper = localFont({
  src: "../../public/fonts/GrimReaper-jEBRO.ttf",
  variable: "--font-custom",
  weight: "400",
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={grimReaper.variable}>
      <body>{children}</body>
    </html>
  );
}
